### ISSUE TITLE
What is the purple domain

### ISSUE THREAD

**Issue by mycrobe** [warelab/gramene-genetree-vis#54]
The purple domain (see below) does not bring up its own a popup when clicked; it's that of the orange domain. What's going on?

<img width="1217" alt="screen shot 2016-09-01 at 9 47 32 am" src="https://cloud.githubusercontent.com/assets/40182/18169670/3563f18a-7029-11e6-9813-6213cda34d2a.png">

(Gene is AT2G37700)

**Comment by ajo2995** [comment]
<img width="726" alt="screen shot 2016-09-06 at 4 42 23 pm" src="https://cloud.githubusercontent.com/assets/1328413/18290290/f44390e4-7450-11e6-9916-5703ac47003d.png">

The purple domain is contained within the orange domain, it is rendered on top of the orange one, but the region you can click on corresponds to the orange domain. This is a bug in the interactivity.
