### ISSUE TITLE
wire up display mode dropdown

### ISSUE THREAD

**Issue by ajo2995** [warelab/gramene-genetree-vis#69]
There is a dropdown menu to let the user choose the display mode. The default is “domains” (see initial state). It needs to be wired it up to switch on the multiple sequence alignment (displayMode "msa") and eventually other modes ("phyloview", "expression", "science")

Both the "domains" and "msa" modes need to have the zoomer interface (which admittedly needs help), but the phyloview mode won’t

**Comment by thomasoniii** [comment]
Wired up in #72.
